/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/CarritoView': RouteRecordInfo<'/CarritoView', '/CarritoView', Record<never, never>, Record<never, never>>,
    '/DetalleProducto': RouteRecordInfo<'/DetalleProducto', '/DetalleProducto', Record<never, never>, Record<never, never>>,
    '/Home': RouteRecordInfo<'/Home', '/Home', Record<never, never>, Record<never, never>>,
    '/ListadoProductosVueConRouter': RouteRecordInfo<'/ListadoProductosVueConRouter', '/ListadoProductosVueConRouter', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/Registro': RouteRecordInfo<'/Registro', '/Registro', Record<never, never>, Record<never, never>>,
  }
}
